CREATE TABLE products (
    ID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Status VARCHAR(10) DEFAULT 'pending' NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);